// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0w-Cm8zq0wbt307EiyvE0OezGWxWLIts',
    appId: '1:764909508771:web:e9b89e7165a244b5d88716',
    messagingSenderId: '764909508771',
    projectId: 'smartfarmassistant',
    authDomain: 'smartfarmassistant.firebaseapp.com',
    storageBucket: 'smartfarmassistant.firebasestorage.app',
    measurementId: 'G-6PLFZBNTP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlOMSC2dO-P7PilPQwdoRgjAmwfcrcIkQ',
    appId: '1:764909508771:android:7d85d1d9a2194b35d88716',
    messagingSenderId: '764909508771',
    projectId: 'smartfarmassistant',
    storageBucket: 'smartfarmassistant.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs-3eoxe2ViJ9TOacqBEgrfy9nIRXk80U',
    appId: '1:764909508771:ios:56b9f5e3337a1bfad88716',
    messagingSenderId: '764909508771',
    projectId: 'smartfarmassistant',
    storageBucket: 'smartfarmassistant.firebasestorage.app',
    iosBundleId: 'com.dev.kl.uniProject',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs-3eoxe2ViJ9TOacqBEgrfy9nIRXk80U',
    appId: '1:764909508771:ios:56b9f5e3337a1bfad88716',
    messagingSenderId: '764909508771',
    projectId: 'smartfarmassistant',
    storageBucket: 'smartfarmassistant.firebasestorage.app',
    iosBundleId: 'com.dev.kl.uniProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0w-Cm8zq0wbt307EiyvE0OezGWxWLIts',
    appId: '1:764909508771:web:673d50e2a72520b0d88716',
    messagingSenderId: '764909508771',
    projectId: 'smartfarmassistant',
    authDomain: 'smartfarmassistant.firebaseapp.com',
    storageBucket: 'smartfarmassistant.firebasestorage.app',
    measurementId: 'G-JV8KD9SBPG',
  );
}
